### ISSUE TITLE
projectのアクションを通知

### ISSUE THREAD

**Issue by shu920921** [kutsuzawa/gitnotification#9]
githubが`github/webhook/projects`にpostすると、hubotがslcakに内容を表示する。

**Comment by ryo2851** [comment]
PaaS内に永続ファイル持てない問題に直面.
columnがaddされたときにjsonファイルを追加すればいいかと思ったがそれだと `heroku create` とかってもっかいやる際にファイルを保持できない。
DBに保持するとしたら, PaaS内からアクセス可能なサーバにDBを配置する必要有

**Comment by ryo2851** [comment]
hogehoge-gibot からアクセス可能な場所にDBを構築する必要があり、そのためにheroku PostgreSQLを用いた。
kutsuzawa-gibot内にDBを配置し、それ以外のアプリはそのDBをshareして使うようにした。
設定はwikiに書いた。
https://github.com/kutsuzawa/gitnotification/wiki/postgre
